server:
  port: 9001
  servlet:
    context-path: /student

spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    username: ${MYSQL_ROOT_USER}
    url: jdbc:mysql://localhost:3306/student
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
