server:
  port: 9093

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/richieoscar/schoolServicesConfigServer
          clone-on-start: true