server:
  port: 9000
  servlet:
    context-path: /department

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/department
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost