server:
  port: 9000
  servlet:
    context-path: /department

spring:
  application:
    name: DEPARTMENT-SERVICE

  config:
    import: optional:configserver:http://localhost:9093

  zipkin:
    base-url: http://localhost:9411

  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/department
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show_sql: true
